trigger:
  branches:
    include: [ "*" ]
  tags:
    include: [ "*" ]

pool:
  name: WS

resources:
  repositories:
  - repository: AZ-CI
  
stages: 
- stage: CodeQuality Stage
  displayName: 'Checking the Code Quailty Stage'
  jobs:
  - templates: codeCheck.yml@AZ