trigger:
  branches:
    include: [ "*" ]
  tags:
    include: [ "*" ]

pool:
  name: WS

stages:
  - stage: CodeQualityStage
    displayName : 'Code Quality Stage'
    jobs:
    - job: 'Submitting the Code for Quality Check'
      displayName: 'Submit Stage'
      steps: 
      - script : |
          echo " Code is submitted for the Quality check.
        displayName : 'Submit Stage'
    - job: 'CodeQuality Report'
      displayName : 'CodeQuality Report'
      steps:
      - script : |
          echo "Code Quality is Good"
        displayName: 'Result stage'


