trigger:
  branches:
    include: [ "*" ]
  tags:
    include: [ "*" ]

pool:
  name: WS

stages:
  - stage: CodeQualityStage
    displayName : 'Code Quality Stage'
    jobs:
    - job: SubmitStage
      displayName: 'Job to submit code for  Quality check'
      steps: 
      - script : |
          echo " Code is submitted for the Quality check."
        displayName : 'Submited code'
    - job: CodeQualityReport
      displayName : 'CodeQuality Report Job'
      dependsOn : SubmitStage
      steps:
      - script : |
          echo "Code Quality is Good"
        displayName: 'Result'
  
  - stage: TestingStage
    displayName : 'Code Test Stage'
    jobs:
    - job: UnitTestStage
      displayName: 'job to do Unit tests'
      steps: 
      - script : |
          echo "Code test passed."
        displayName : 'Unit test'
    - job: LintCheckStage
      displayName : 'Code Lint checking Job'
      steps:
      - script : |
          echo "Code lint is Good"
        displayName: 'Lint checking'
        
  - stage: ArtifactsStage
    displayName : 'Artifacts Stage'
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    jobs:
    - job: Preparing_Artifacts
      displayName: 'preparing the Artifacts Job'
      steps: 
      - script : |
          env
          npm install
          cp -r node_modules server.js $(Build.BinariesDirectory)/.
        displayName : 'preparing the Artifacts'
    - job: publishing_Artifacts
      displayName : 'Publsihing Artifacts Job'
      dependsOn : Preparing_Artifacts
      steps:
      - script : |
          cd $(Build.BinariesDirectory)
          az artifacts universal publish --organization https://dev.azure.com/dasarisaikrishna97/ --project="Roboshop" --scope project --feed WS --name cart --version ${BUILD_SOURCEBRANCHNAME} --description "Welcome to Universal Packages" --path .
        displayName: 'Publishing Artifacts'