trigger:
  branches:
    include: [ "*" ]
  tags:
    include: [ "*" ]

pool:
  name: WS

stages:
  - stage: CodeQualityStage
    displayName : 'Code Quality Stage'
    jobs:
    - job: SubmitStage
      displayName: 'Submitting the code for Quality check'
      steps: 
      - script : |
          echo " Code is submitted for the Quality check."
        displayName : 'Submit Stage'
    - job: CodeQualityReport
      displayName : 'CodeQuality Report'
      dependsOn : SubmitStage
      steps:
      - script : |
          echo "Code Quality is Good"
        displayName: 'Result stage'
  
  - stage: TestingStage
    displayName : 'Code Test Stage'
    jobs:
    - job: UnitTestStage
      displayName: 'Submitting the code for Unit tests'
      steps: 
      - script : |
          echo "Code test passed."
        displayName : 'Unit test Stage'
    - job: LintCheckStage
      displayName : 'Code Lint checking stage'
      steps:
      - script : |
          echo "Code lint is Good"
        displayName: 'Lint check stage'
